pipeline {
 agent any
  
 stages {
   stage('Checkout') {
     steps {
     // 소스코드 체크아웃
       checkout scm
     }
   }
   stage('Build') {
            steps {
                // Gradle을 사용하여 Java 파일 컴파일
                script {
                    if (isUnix()) {
                        sh './gradlew compileJava'
                    } else {
                        bat 'gradlew.bat compileJava'
                    }
                }
            }
        }
   stage('Test') {
            steps {
                // Gradle을 사용하여 JUnit 테스트 실행
                script {
                    if (isUnix()) {
                        sh './gradlew test'
                    } else {
                        bat 'gradlew.bat test'
                    }
                }
            }
        }
    }
 
 post {
   always {
       // 테스트 결과 파일을 저장하기 위해 아카이브
       archiveArtifacts artifacts: '**/test-results/**/*.xml', allowEmptyArchive: true
   }
   failure {
       echo 'Build or test failed'
   }
   success {
       echo 'Build and test succeeded'
   }
 }
}
    
  
